"""
Pydantic schemas package.
"""

from app.schemas.base import (
    BaseSchema,
    TimestampedSchema,
    PaginationParams,
    PaginatedResponse,
    HealthResponse,
    ErrorResponse,
    SuccessResponse,
    FilterParams,
    MetadataResponse
)

from app.schemas.user import (
    UserRole,
    UserStatus,
    UserBase,
    UserCreate,
    UserUpdate,
    UserLogin,
    UserRegister,
    UserResponse,
    UserDetailResponse,
    UserListParams,
    UserChangePassword,
    UserResetPassword,
    UserSetPassword,
    UserPreferences,
    UserNotificationSettings,
    UserSessionResponse,
    UserAPIKeyCreate,
    UserAPIKeyResponse,
    UserStats,
    UserActivity,
    UserPublicProfile
)

from app.schemas.error import (
    ErrorSeverity,
    ErrorStatus,
    ErrorCategory,
    ErrorBase,
    ErrorCreate,
    ErrorUpdate,
    ErrorResolve,
    ErrorAssign,
    ErrorIgnore,
    ErrorBulkAction,
    ErrorResponse,
    ErrorListParams,
    ErrorAnalysis,
    ErrorAnalysisResponse,
    ErrorOccurrence,
    ErrorStatistics,
    ErrorMetrics,
    ErrorPattern,
    ErrorDuplicate,
    ErrorExport,
    ErrorImport,
    ErrorWebhook,
    ErrorAlert
)

from app.schemas.fix import (
    FixType,
    FixStatus,
    FixRiskLevel,
    FixBase,
    FixCreate,
    FixUpdate,
    FixApprove,
    FixReject,
    FixApply,
    FixRollback,
    FixTestResult,
    FixBulkAction,
    FixGenerate,
    FixValidate,
    FixResponse,
    FixListParams,
    FixValidationResult,
    FixTestSummary,
    FixApproval,
    FixApplication,
    FixMetrics,
    FixTemplate,
    FixExport,
    FixImport,
    FixWebhook
)

__all__ = [
    # Base schemas
    "BaseSchema",
    "TimestampedSchema",
    "PaginationParams",
    "PaginatedResponse",
    "HealthResponse",
    "ErrorResponse",
    "SuccessResponse",
    "FilterParams",
    "MetadataResponse",

    # User schemas
    "UserRole",
    "UserStatus",
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserLogin",
    "UserRegister",
    "UserResponse",
    "UserDetailResponse",
    "UserListParams",
    "UserChangePassword",
    "UserResetPassword",
    "UserSetPassword",
    "UserPreferences",
    "UserNotificationSettings",
    "UserSessionResponse",
    "UserAPIKeyCreate",
    "UserAPIKeyResponse",
    "UserStats",
    "UserActivity",
    "UserPublicProfile",

    # Error schemas
    "ErrorSeverity",
    "ErrorStatus",
    "ErrorCategory",
    "ErrorBase",
    "ErrorCreate",
    "ErrorUpdate",
    "ErrorResolve",
    "ErrorAssign",
    "ErrorIgnore",
    "ErrorBulkAction",
    "ErrorResponse",
    "ErrorListParams",
    "ErrorAnalysis",
    "ErrorAnalysisResponse",
    "ErrorOccurrence",
    "ErrorStatistics",
    "ErrorMetrics",
    "ErrorPattern",
    "ErrorDuplicate",
    "ErrorExport",
    "ErrorImport",
    "ErrorWebhook",
    "ErrorAlert",

    # Fix schemas
    "FixType",
    "FixStatus",
    "FixRiskLevel",
    "FixBase",
    "FixCreate",
    "FixUpdate",
    "FixApprove",
    "FixReject",
    "FixApply",
    "FixRollback",
    "FixTestResult",
    "FixBulkAction",
    "FixGenerate",
    "FixValidate",
    "FixResponse",
    "FixListParams",
    "FixValidationResult",
    "FixTestSummary",
    "FixApproval",
    "FixApplication",
    "FixMetrics",
    "FixTemplate",
    "FixExport",
    "FixImport",
    "FixWebhook",
]